// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hY-Y99scsS_RGnGcSy1dN16FjQ8_j3I',
    appId: '1:93729394583:web:aa6f86c0458b1698ab7ed2',
    messagingSenderId: '93729394583',
    projectId: 'flutter-firebase-playgro-58337',
    authDomain: 'flutter-firebase-playgro-58337.firebaseapp.com',
    storageBucket: 'flutter-firebase-playgro-58337.firebasestorage.app',
    measurementId: 'G-041C4EZCEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgnASNE6nim-G1b8CYstIohzRUgM2lro',
    appId: '1:93729394583:android:b860a423da5a10f7ab7ed2',
    messagingSenderId: '93729394583',
    projectId: 'flutter-firebase-playgro-58337',
    storageBucket: 'flutter-firebase-playgro-58337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaOVjy4po_4XjWVaqlwRr8dooUzLE6adY',
    appId: '1:93729394583:ios:ded1e8e72b447087ab7ed2',
    messagingSenderId: '93729394583',
    projectId: 'flutter-firebase-playgro-58337',
    storageBucket: 'flutter-firebase-playgro-58337.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebasePlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaOVjy4po_4XjWVaqlwRr8dooUzLE6adY',
    appId: '1:93729394583:ios:ded1e8e72b447087ab7ed2',
    messagingSenderId: '93729394583',
    projectId: 'flutter-firebase-playgro-58337',
    storageBucket: 'flutter-firebase-playgro-58337.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebasePlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1hY-Y99scsS_RGnGcSy1dN16FjQ8_j3I',
    appId: '1:93729394583:web:7ef2ff2782225b2cab7ed2',
    messagingSenderId: '93729394583',
    projectId: 'flutter-firebase-playgro-58337',
    authDomain: 'flutter-firebase-playgro-58337.firebaseapp.com',
    storageBucket: 'flutter-firebase-playgro-58337.firebasestorage.app',
    measurementId: 'G-R6B6D1FDNK',
  );
}
